### ISSUE TITLE
Bot is not responding

### ISSUE THREAD

**Issue by aptrishu** [hartleybrody/fb-messenger-bot#11]
My Bot is not respoding, while it was responding earlier.

>2016-12-03T08:17:05.068685+00:00 app[web.1]: {u'entry': [{u'messaging': [{u'recipient': {u'id': u'636962749808826'}, u'sender': {u'id': u'1241533192597972'}, u'message': {u'seq': 59, u'mid': u'mid.1480751968104:11c4dfda59', u'sticker_id': 227878347358915, u'attachments': [{u'type': u'image', u'payload': {u'url': u'https://scontent.xx.fbcdn.net/t39.1997-6/851577_246547505491999_862435009_n.png?_nc_ad=z-m', u'sticker_id': 227878347358915}}]}, u'timestamp': 1480751968104}], u'time': 1480753024903, u'id': u'636962749808826'}], u'object': u'page'}
2016-12-03T08:17:05.069312+00:00 app[web.1]: [2016-12-03 08:17:05,068] ERROR in app: Exception on / [POST]
2016-12-03T08:17:05.069315+00:00 app[web.1]: Traceback (most recent call last):
2016-12-03T08:17:05.069316+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
2016-12-03T08:17:05.069317+00:00 app[web.1]:     response = self.full_dispatch_request()
2016-12-03T08:17:05.069317+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
2016-12-03T08:17:05.069318+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2016-12-03T08:17:05.069319+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
2016-12-03T08:17:05.069319+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2016-12-03T08:17:05.069320+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
2016-12-03T08:17:05.069320+00:00 app[web.1]:     rv = self.dispatch_request()
2016-12-03T08:17:05.069321+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
2016-12-03T08:17:05.069322+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2016-12-03T08:17:05.069322+00:00 app[web.1]:   File "/app/app.py", line 40, in webhook
2016-12-03T08:17:05.069323+00:00 app[web.1]:     message_text = messaging_event["message"]["text"]  # the message's text
2016-12-03T08:17:05.069324+00:00 app[web.1]: KeyError: 'text'
2016-12-03T08:17:05.050246+00:00 heroku[router]: at=info method=POST path="/" host=vast-badlands-53174.herokuapp.com request_id=0bc53e1c-91ce-48de-8423-2de6cf46cb65 fwd="69.63.188.112" dyno=web.1 connect=1ms service=9ms status=500 bytes=456

**Comment by hartleybrody** [comment]
Since this is free template code, I don't offer support but I'll leave you with in the hopes that it helps you figure things out on your own :)

[Debugging Tips for Beginners: How to Troubleshoot and Fix Your Code Without Pulling Your Hair Out](https://blog.hartleybrody.com/debugging-code-beginner/)
