### ISSUE TITLE
The URL couldn't be validated.

### ISSUE THREAD

**Issue by datomnurdin** [hartleybrody/fb-messenger-bot#4]
I got this error message when setup the webhook

```
The URL couldn't be validated. Callback verification failed with the following errors: HTTP Status Code = 500; HTTP Message = INTERNAL SERVER ERROR
```

![screenshot 2016-08-15 03 49 07](https://cloud.githubusercontent.com/assets/5416242/17651495/ca20a7c4-629a-11e6-8427-824d14b723d5.png)

Please advice. Thank you

**Comment by hartleybrody** [comment]
If facebook is reporting a 500 error when trying to access the URL, then there's some sort of error happening on the server side. You heroku logs will give you the python stacktrace telling you what's broken.

Without seeing those, if you didn't change any of the code then my wild guess is that you didn't set one of the two required environment variables correctly. If you post the stacktrace from your Heroku logs that'll give us more information too work with.

**Comment by datomnurdin** [comment]
I already setup PAGE_ACCESS_TOKEN and VERIFY_TOKEN, still same.

**Comment by hartleybrody** [comment]
Well if my wild guess isn't right, then it'd be extra helpful if you posted your Heroku application's logs.

**Comment by datomnurdin** [comment]
Here is the log

```
2016-08-14T19:43:34.255799+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2016-08-14T19:43:34.255800+00:00 app[web.1]:   File "/app/app.py", line 16, in verify
2016-08-14T19:43:34.255801+00:00 app[web.1]:     if not request.args.get("hub.verify_token") == os.environ["VERIFY_TOKEN"]:
2016-08-14T19:43:34.255802+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/UserDict.py", line 40, in __getitem__
2016-08-14T19:43:34.255803+00:00 app[web.1]:     raise KeyError(key)
2016-08-14T19:43:34.255803+00:00 app[web.1]: KeyError: 'VERIFY_TOKEN'
2016-08-14T19:47:33.209477+00:00 heroku[router]: at=info method=GET path="/?hub.mode=subscribe&hub.challenge=673489068&hub.verify_token=EAAOcZCe5GQd4BAJ5TqktzBggiTioOFkJRLUjbvtbFEArHZCBlJZCc3WntGcFzoyTriU2JzbxGGQQICeLChSOno2J96DxYd5ySG102GL5ib37GmZBJw09zBM9ZBiZBnCbMAlM0GpKwiZBuUOgTyjEiaOzFT8KsiVwNLm0pSNWzXVaAZDZD" host=fb-messenger-bot-intellij.herokuapp.com request_id=aec09296-c1b1-4796-a107-23b52d44b157 fwd="69.171.230.98" dyno=web.1 connect=1ms service=3ms status=500 bytes=456
2016-08-14T19:47:33.175998+00:00 app[web.1]: [2016-08-14 19:47:33,175] ERROR in app: Exception on / [GET]
2016-08-14T19:47:33.176012+00:00 app[web.1]: Traceback (most recent call last):
2016-08-14T19:47:33.176013+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
2016-08-14T19:47:33.176014+00:00 app[web.1]:     response = self.full_dispatch_request()
2016-08-14T19:47:33.176015+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
2016-08-14T19:47:33.176016+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2016-08-14T19:47:33.176017+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
2016-08-14T19:47:33.176017+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2016-08-14T19:47:33.176018+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
2016-08-14T19:47:33.176019+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
2016-08-14T19:47:33.176020+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2016-08-14T19:47:33.176019+00:00 app[web.1]:     rv = self.dispatch_request()
2016-08-14T19:47:33.176021+00:00 app[web.1]:   File "/app/app.py", line 16, in verify
2016-08-14T19:47:33.176022+00:00 app[web.1]:     if not request.args.get("hub.verify_token") == os.environ["VERIFY_TOKEN"]:
2016-08-14T19:47:33.176023+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/UserDict.py", line 40, in __getitem__
2016-08-14T19:47:33.176024+00:00 app[web.1]:     raise KeyError(key)
2016-08-14T19:47:33.176024+00:00 app[web.1]: KeyError: 'VERIFY_TOKEN'
2016-08-14T19:47:43.142594+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
2016-08-14T19:47:43.142591+00:00 app[web.1]: Traceback (most recent call last):
2016-08-14T19:47:43.142593+00:00 app[web.1]:     response = self.full_dispatch_request()
2016-08-14T19:47:43.142595+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
2016-08-14T19:47:43.142597+00:00 app[web.1]:     rv = self.dispatch_request()
2016-08-14T19:47:43.142598+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
2016-08-14T19:47:43.142599+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2016-08-14T19:47:43.142592+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
2016-08-14T19:47:43.142601+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/UserDict.py", line 40, in __getitem__
2016-08-14T19:47:43.142570+00:00 app[web.1]: [2016-08-14 19:47:43,142] ERROR in app: Exception on / [GET]
2016-08-14T19:47:43.142596+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2016-08-14T19:47:43.142597+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
2016-08-14T19:47:43.142602+00:00 app[web.1]:     raise KeyError(key)
2016-08-14T19:47:43.142603+00:00 app[web.1]: KeyError: 'VERIFY_TOKEN'
2016-08-14T19:47:43.142595+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2016-08-14T19:47:43.142599+00:00 app[web.1]:   File "/app/app.py", line 16, in verify
2016-08-14T19:47:43.142600+00:00 app[web.1]:     if not request.args.get("hub.verify_token") == os.environ["VERIFY_TOKEN"]:
2016-08-14T19:47:43.164230+00:00 heroku[router]: at=info method=GET path="/?hub.mode=subscribe&hub.challenge=1320983164&hub.verify_token=EAAOcZCe5GQd4BAJ5TqktzBggiTioOFkJRLUjbvtbFEArHZCBlJZCc3WntGcFzoyTriU2JzbxGGQQICeLChSOno2J96DxYd5ySG102GL5ib37GmZBJw09zBM9ZBiZBnCbMAlM0GpKwiZBuUOgTyjEiaOzFT8KsiVwNLm0pSNWzXVaAZDZD" host=fb-messenger-bot-intellij.herokuapp.com request_id=07a082e2-d49d-4c2d-8323-47c3c6b8bda1 fwd="69.171.230.117" dyno=web.1 connect=1ms service=2ms status=500 bytes=456
2016-08-14T19:47:49.316154+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
2016-08-14T19:47:49.316152+00:00 app[web.1]: Traceback (most recent call last):
2016-08-14T19:47:49.316135+00:00 app[web.1]: [2016-08-14 19:47:49,315] ERROR in app: Exception on / [GET]
2016-08-14T19:47:49.316156+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
2016-08-14T19:47:49.316154+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2016-08-14T19:47:49.316155+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2016-08-14T19:47:49.316152+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
2016-08-14T19:47:49.316155+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
2016-08-14T19:47:49.316153+00:00 app[web.1]:     response = self.full_dispatch_request()
2016-08-14T19:47:49.316156+00:00 app[web.1]:     rv = self.dispatch_request()
2016-08-14T19:47:49.316157+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
2016-08-14T19:47:49.316159+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/UserDict.py", line 40, in __getitem__
2016-08-14T19:47:49.316157+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2016-08-14T19:47:49.316158+00:00 app[web.1]:     if not request.args.get("hub.verify_token") == os.environ["VERIFY_TOKEN"]:
2016-08-14T19:47:49.316157+00:00 app[web.1]:   File "/app/app.py", line 16, in verify
2016-08-14T19:47:49.316160+00:00 app[web.1]: KeyError: 'VERIFY_TOKEN'
2016-08-14T19:47:49.316159+00:00 app[web.1]:     raise KeyError(key)
2016-08-14T19:47:49.317539+00:00 heroku[router]: at=info method=GET path="/?hub.mode=subscribe&hub.challenge=495442390&hub.verify_token=EAAOcZCe5GQd4BAJ5TqktzBggiTioOFkJRLUjbvtbFEArHZCBlJZCc3WntGcFzoyTriU2JzbxGGQQICeLChSOno2J96DxYd5ySG102GL5ib37GmZBJw09zBM9ZBiZBnCbMAlM0GpKwiZBuUOgTyjEiaOzFT8KsiVwNLm0pSNWzXVaAZDZD" host=fb-messenger-bot-intellij.herokuapp.com request_id=cc175d30-7b1c-4f7e-b0d9-ec393c422751 fwd="69.171.230.99" dyno=web.1 connect=1ms service=3ms status=500 bytes=456
2016-08-14T20:17:56.338709+00:00 heroku[api]: Set VERIFY_TOKEN config vars by nurdin@intellij.my
2016-08-14T20:17:56.338777+00:00 heroku[api]: Release v7 created by nurdin@intellij.my
2016-08-14T20:17:56.598754+00:00 heroku[web.1]: Restarting
2016-08-14T20:17:56.599276+00:00 heroku[web.1]: State changed from up to starting
2016-08-14T20:17:59.038651+00:00 heroku[web.1]: Starting process with command `gunicorn app:app --log-file=-`
2016-08-14T20:17:59.342041+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2016-08-14T20:17:59.931256+00:00 app[web.1]: [2016-08-14 20:17:59 +0000] [9] [INFO] Worker exiting (pid: 9)
2016-08-14T20:17:59.931269+00:00 app[web.1]: [2016-08-14 20:17:59 +0000] [12] [INFO] Worker exiting (pid: 12)
2016-08-14T20:17:59.931336+00:00 app[web.1]: [2016-08-14 20:17:59 +0000] [3] [INFO] Handling signal: term
2016-08-14T20:17:59.966569+00:00 app[web.1]: [2016-08-14 20:17:59 +0000] [3] [INFO] Shutting down: Master
2016-08-14T20:18:00.054018+00:00 heroku[web.1]: Process exited with status 0
2016-08-14T20:18:01.150203+00:00 app[web.1]: [2016-08-14 20:18:01 +0000] [3] [INFO] Starting gunicorn 19.6.0
2016-08-14T20:18:01.150753+00:00 app[web.1]: [2016-08-14 20:18:01 +0000] [3] [INFO] Listening at: http://0.0.0.0:8079 (3)
2016-08-14T20:18:01.150853+00:00 app[web.1]: [2016-08-14 20:18:01 +0000] [3] [INFO] Using worker: sync
2016-08-14T20:18:01.155049+00:00 app[web.1]: [2016-08-14 20:18:01 +0000] [9] [INFO] Booting worker with pid: 9
2016-08-14T20:18:01.219337+00:00 app[web.1]: [2016-08-14 20:18:01 +0000] [12] [INFO] Booting worker with pid: 12
2016-08-14T20:18:02.682265+00:00 heroku[web.1]: State changed from starting to up
2016-08-14T20:18:03.721850+00:00 heroku[router]: at=info method=GET path="/?hub.mode=subscribe&hub.challenge=5318636&hub.verify_token=h6YzXRSoMRc8IcbMWFjs" host=fb-messenger-bot-intellij.herokuapp.com request_id=fa35afac-e004-4a29-82ae-fb9e7cb4c11d fwd="69.171.230.117" dyno=web.1 connect=0ms service=1ms status=403 bytes=194
2016-08-14T20:18:09.296064+00:00 heroku[router]: at=info method=GET path="/?hub.mode=subscribe&hub.challenge=1838009564&hub.verify_token=h6YzXRSoMRc8IcbMWFjs" host=fb-messenger-bot-intellij.herokuapp.com request_id=4e5d1e66-d11b-4e28-9776-19c719cca353 fwd="69.171.230.115" dyno=web.1 connect=0ms service=2ms status=403 bytes=194
2016-08-14T20:18:11.361799+00:00 heroku[router]: at=info method=GET path="/?hub.mode=subscribe&hub.challenge=2104267924&hub.verify_token=h6YzXRSoMRc8IcbMWFjs" host=fb-messenger-bot-intellij.herokuapp.com request_id=bf9aa3d9-0d63-4106-bd49-2d1dd854296a fwd="66.220.149.34" dyno=web.1 connect=0ms service=5ms status=403 bytes=194
2016-08-14T20:18:12.541544+00:00 heroku[router]: at=info method=GET path="/?hub.mode=subscribe&hub.challenge=253602840&hub.verify_token=h6YzXRSoMRc8IcbMWFjs" host=fb-messenger-bot-intellij.herokuapp.com request_id=038aa4ed-b47d-41d9-a820-d232af3b0d96 fwd="69.171.230.121" dyno=web.1 connect=0ms service=9ms status=403 bytes=194
2016-08-14T20:19:00.584162+00:00 heroku[router]: at=info method=GET path="/?hub.mode=subscribe&hub.challenge=575758171&hub.verify_token=h6YzXRSoMRc8IcbMWFjs" host=fb-messenger-bot-intellij.herokuapp.com request_id=93f8d3ee-520d-4a98-832d-133888a3563f fwd="69.171.230.119" dyno=web.1 connect=1ms service=4ms status=403 bytes=194
2016-08-14T20:19:14.084508+00:00 heroku[api]: Set PAGE_ACCESS_TOKEN config vars by nurdin@intellij.my
2016-08-14T20:19:14.084508+00:00 heroku[api]: Release v8 created by nurdin@intellij.my
2016-08-14T20:19:14.426633+00:00 heroku[web.1]: Restarting
2016-08-14T20:19:14.427432+00:00 heroku[web.1]: State changed from up to starting
2016-08-14T20:19:16.814929+00:00 heroku[web.1]: Starting process with command `gunicorn app:app --log-file=-`
2016-08-14T20:19:17.555565+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2016-08-14T20:19:18.322289+00:00 app[web.1]: [2016-08-14 20:19:18 +0000] [9] [INFO] Worker exiting (pid: 9)
2016-08-14T20:19:18.322303+00:00 app[web.1]: [2016-08-14 20:19:18 +0000] [12] [INFO] Worker exiting (pid: 12)
2016-08-14T20:19:18.322707+00:00 app[web.1]: [2016-08-14 20:19:18 +0000] [3] [INFO] Handling signal: term
2016-08-14T20:19:18.326243+00:00 app[web.1]: [2016-08-14 20:19:18 +0000] [3] [INFO] Shutting down: Master
2016-08-14T20:19:18.404434+00:00 heroku[web.1]: Process exited with status 0
2016-08-14T20:19:18.820505+00:00 app[web.1]: [2016-08-14 20:19:18 +0000] [3] [INFO] Listening at: http://0.0.0.0:58301 (3)
2016-08-14T20:19:18.820639+00:00 app[web.1]: [2016-08-14 20:19:18 +0000] [3] [INFO] Using worker: sync
2016-08-14T20:19:18.819873+00:00 app[web.1]: [2016-08-14 20:19:18 +0000] [3] [INFO] Starting gunicorn 19.6.0
2016-08-14T20:19:18.825320+00:00 app[web.1]: [2016-08-14 20:19:18 +0000] [9] [INFO] Booting worker with pid: 9
2016-08-14T20:19:18.882653+00:00 app[web.1]: [2016-08-14 20:19:18 +0000] [12] [INFO] Booting worker with pid: 12
2016-08-14T20:19:20.483983+00:00 heroku[web.1]: State changed from starting to up
2016-08-14T20:19:27.400541+00:00 heroku[router]: at=info method=GET path="/?hub.mode=subscribe&hub.challenge=2139080915&hub.verify_token=h6YzXRSoMRc8IcbMWFjs" host=fb-messenger-bot-intellij.herokuapp.com request_id=b0edf403-8f55-4cb9-9d0a-f5aa862d6ad6 fwd="69.171.230.109" dyno=web.1 connect=1ms service=3ms status=403 bytes=194
2016-08-14T20:21:00.558295+00:00 heroku[router]: at=info method=GET path="/?hub.mode=subscribe&hub.challenge=1698553166&hub.verify_token=h6YzXRSoMRc8IcbMWFjs" host=fb-messenger-bot-intellij.herokuapp.com request_id=43ae9716-cc61-486d-b029-d6db66bceeb4 fwd="69.171.230.102" dyno=web.1 connect=1ms service=3ms status=403 bytes=194
```

**Comment by hartleybrody** [comment]
What do you know, my wild guess what right!

`KeyError: 'VERIFY_TOKEN'`

You'll have to set them using:

`heroku config:add VERIFY_TOKEN=$whatever_value_you_gave_facebook`

as I mentioned in step [#4 of the tutorial](https://blog.hartleybrody.com/fb-messenger-bot/).

**Comment by datomnurdin** [comment]
I already followed your instruction but it still shown the same error message.

**Comment by katiearriagam** [comment]
What does it mean if, instead of KeyError: 'VERIFY_TOKEN', it shows KeyError: 'text'?

**Comment by hartleybrody** [comment]
For new issues, please start a new "issue" on github so they're not all mixed together. Also, please include a full stacktrace of the error you're getting.
